# Generated by Django 3.1.1 on 2020-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Неопределено', 'Неопределено'), ('Заросло', 'Заросло'), ('Изменение границ', 'Изменение границ')], max_length=20)),
                ('area', models.CharField(max_length=256)),
                ('coordinates', models.CharField(max_length=256)),
                ('image_link', models.CharField(max_length=256)),
            ],
        ),
    ]
